version: '3'
services:
  master:
    hostname: master
    image: bucket98/locust:0.8
    environment:
      LOCUST_MODE: master
    ports:
      - "8089:8089"
    volumes:
      - ./src:/locust
    command: -f locustfile.py --master -H http://master:8089
  worker:
    hostname: worker
    image: bucket98/locust:0.8
    environment:
      ATTACKED_HOST: http://master:8089
      LOCUST_MODE: worker
    volumes:
      - ./src:/locust
    command: -f locustfile.py --worker --master-host master

